[application]

# App (Project) Name
name = "daniel-mason-cv"


# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Daniel Mason CV"

#base_path = "cv"

[web.watcher]

index_on_404 = true
